version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: filemonitoring_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: FileMonitoringDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - filemonitoring_network

volumes:
  postgres_data:

networks:
  filemonitoring_network:
    driver: bridge